import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import { glob } from 'tinyglobby'

const rootDir = fileURLToPath(new URL('..', import.meta.url))

const SOURCE_GLOBS = [
  'app/**/*.{vue,ts,tsx,js,jsx,mjs,cjs}',
  'lib/**/*.{ts,js,mjs}',
  'shared/**/*.{ts,js,mjs}',
  'server/**/*.{ts,js,mjs}'
]

const ICON_FILE_PATH = path.join(rootDir, 'lib', 'icon.ts')

const colonPattern = /(['"`])([a-z0-9-]+:[a-z0-9-]+)\1/gi
const prefixedPattern = /(['"`])(i-[a-z0-9-]+(?:-[a-z0-9-]+)+)\1/gi

const normalizeIconName = (raw) => {
  if (raw.startsWith('i-')) {
    const [, prefix, ...rest] = raw.split('-')
    if (!prefix || rest.length === 0) {
      return null
    }
    return `${prefix}:${rest.join('-')}`
  }
  return raw
}

const extractIcons = (content, regex) => {
  const matches = []
  let match = regex.exec(content)
  while (match) {
    matches.push(match[2])
    match = regex.exec(content)
  }
  return matches
}

const pkg = JSON.parse(
  await readFile(path.join(rootDir, 'package.json'), 'utf-8')
)
const pkgDeps = { ...(pkg.dependencies || {}), ...(pkg.devDependencies || {}) }
const packagePrefixes = Object.keys(pkgDeps)
  .filter((name) => name.startsWith('@iconify-json/'))
  .map((name) => name.replace('@iconify-json/', ''))

const EXTRA_PREFIXES = ['simple-icons', 'fluent-emoji-flat', 'iconoir']
const allowedPrefixes = new Set([...packagePrefixes, ...EXTRA_PREFIXES])

const files = await glob(SOURCE_GLOBS, {
  cwd: rootDir,
  dot: false,
  absolute: true,
  ignore: ['**/node_modules/**', '**/.nuxt/**', '**/.output/**', '**/dist/**']
})

const iconSet = new Set()

const tryAddIcon = (icon) => {
  if (!icon) return
  const [prefix] = icon.split(':')
  if (allowedPrefixes.has(prefix)) {
    iconSet.add(icon)
  }
}

for (const file of files) {
  const content = await readFile(file, 'utf-8')

  for (const icon of extractIcons(content, colonPattern)) {
    tryAddIcon(icon)
  }

  for (const icon of extractIcons(content, prefixedPattern)) {
    const normalized = normalizeIconName(icon)
    tryAddIcon(normalized)
  }
}

const iconNames = [...iconSet].sort()
const iconCollections = [
  ...new Set(iconNames.map((icon) => icon.split(':')[0]))
].sort()

const fileContent = `/**
 * Auto-generated by scripts/generate-icon-list.mjs
 * Run \`node scripts/generate-icon-list.mjs\` after updating icon usage.
 */
export const ICON_NAMES: string[] = [
${iconNames.map((icon) => `  '${icon}'`).join(',\n')}
]

export const ICON_COLLECTIONS: string[] = [
${iconCollections.map((icon) => `  '${icon}'`).join(',\n')}
]
`

await writeFile(ICON_FILE_PATH, fileContent, 'utf-8')

console.log(`Collected ${iconNames.length} icons from ${files.length} files.`)
console.log(`Wrote ${ICON_FILE_PATH}.`)
